import type { FactPackRiskSignals, Target } from '../types/index.js';
import { getRequiredDetailedDocLinks, getRootDocContract } from './docs-contract.js';

export interface RootQualityIssue {
  code:
    | 'disallowed-pattern'
    | 'missing-heading'
    | 'too-short'
    | 'too-long'
    | 'too-large'
    | 'low-command-coverage'
    | 'missing-warning-topic'
    | 'missing-detailed-doc-links'
    | 'missing-prerequisite-step'
    | 'missing-risk-signal';
  message: string;
  reference: string;
}

const BLOCKING_ROOT_ISSUE_CODES = new Set<RootQualityIssue['code']>([
  'disallowed-pattern',
  'missing-heading',
  'too-short',
  'too-long',
  'too-large',
  'missing-warning-topic',
  'missing-detailed-doc-links',
  'missing-prerequisite-step',
]);

export interface EvaluateRootQualityInput {
  target: Target;
  rootContent: string;
  scripts: Record<string, string>;
  generatedDetailedDocs: string[];
  riskSignals: FactPackRiskSignals;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function hasHeading(content: string, heading: string): boolean {
  const headingPattern = new RegExp(`^\\s*#{1,6}\\s*${escapeRegExp(heading)}\\s*:?\\s*$`, 'im');
  if (headingPattern.test(content)) {
    return true;
  }

  const loosePattern = new RegExp(`\\b${escapeRegExp(heading)}\\b`, 'i');
  return loosePattern.test(content);
}

function getSectionContent(content: string, heading: string): string | null {
  const headingPattern = new RegExp(`^\\s*#{1,6}\\s*${escapeRegExp(heading)}\\s*:?\\s*$`, 'im');
  const match = headingPattern.exec(content);
  if (!match || match.index === undefined) {
    return null;
  }

  const fromHeading = content.slice(match.index + match[0].length);
  const nextHeadingIndex = fromHeading.search(/\n#{1,6}\s+/);
  if (nextHeadingIndex < 0) {
    return fromHeading.trim();
  }

  return fromHeading.slice(0, nextHeadingIndex).trim();
}

function countCommandMentions(content: string, scriptNames: string[]): number {
  let mentions = 0;
  for (const scriptName of scriptNames) {
    const pattern = new RegExp(
      `\\b(?:npm\\s+run|pnpm\\s+|yarn\\s+|bun\\s+run)\\s+${escapeRegExp(scriptName)}\\b`,
      'i',
    );
    if (pattern.test(content)) {
      mentions += 1;
    }
  }
  return mentions;
}

function getWarningTopicPattern(topic: string): RegExp {
  switch (topic) {
    case 'secrets':
      return /\b(secret(?:s)?|api[_ -]?key|credential|token)\b/i;
    case 'generated files':
      return /\b(generated|do not edit|autogenerated|mockserviceworker|llmdocs\.evidence\.json)\b/i;
    case 'breaking changes':
      return /\b(breaking|migration|compatibility|invariant)\b/i;
    case 'validation before handoff':
      return /\b(validate|typecheck|lint|test|quality gate)\b/i;
    default:
      return new RegExp(`\\b${escapeRegExp(topic)}\\b`, 'i');
  }
}

function hasLinkReference(content: string, candidates: string[]): boolean {
  return candidates.some((candidate) => {
    const escaped = escapeRegExp(candidate);
    const rawPattern = new RegExp(escaped, 'i');
    const markdownPattern = new RegExp(`\\[[^\\]]+\\]\\(${escaped}\\)`, 'i');
    return rawPattern.test(content) || markdownPattern.test(content);
  });
}

function buildDetailedDocLinkCandidates(target: Target, canonicalLink: string): string[] {
  if (target === 'cursor') {
    return [
      canonicalLink,
      `./${canonicalLink}`,
      `.cursor/rules/${canonicalLink}`,
      `./.cursor/rules/${canonicalLink}`,
    ];
  }

  return [canonicalLink, `./${canonicalLink}`];
}

function getMissingDetailedDocLinks(content: string, target: Target): string[] {
  const requiredLinks = getRequiredDetailedDocLinks(target);
  return requiredLinks.filter((linkPath) => {
    const candidates = buildDetailedDocLinkCandidates(target, linkPath);
    return !hasLinkReference(content, candidates);
  });
}

function summarizeRiskSignals(riskSignals: FactPackRiskSignals): string[] {
  const checks: string[] = [];
  if (riskSignals.tokenStorageLocalStorage) {
    checks.push('localStorage token handling');
  }
  if (riskSignals.apiMockCoverageGaps.length > 0) {
    checks.push('API/mock coverage gaps');
  }
  if (riskSignals.toolingDependencyGaps.length > 0) {
    checks.push('tooling dependency gaps');
  }
  if (riskSignals.strictTypeScriptFlags.length > 0) {
    checks.push('TypeScript strict gates');
  }
  return checks;
}

export function evaluateRootDocQuality(input: EvaluateRootQualityInput): RootQualityIssue[] {
  const { target, rootContent, scripts, riskSignals } = input;
  const contract = getRootDocContract(target);
  const issues: RootQualityIssue[] = [];
  const nonEmptyLines = rootContent
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  for (const pattern of contract.disallowedPatterns) {
    if (pattern.test(rootContent)) {
      issues.push({
        code: 'disallowed-pattern',
        message: 'Root document contains process/log style content instead of stable instructions.',
        reference: pattern.source,
      });
    }
  }

  if (nonEmptyLines.length < contract.minNonEmptyLines) {
    issues.push({
      code: 'too-short',
      message: `Root document is too short (${nonEmptyLines.length} non-empty lines, expected at least ${contract.minNonEmptyLines}).`,
      reference: String(nonEmptyLines.length),
    });
  }

  if (contract.maxNonEmptyLines && nonEmptyLines.length > contract.maxNonEmptyLines) {
    issues.push({
      code: 'too-long',
      message: `Root document is too long (${nonEmptyLines.length} non-empty lines, expected at most ${contract.maxNonEmptyLines}).`,
      reference: String(nonEmptyLines.length),
    });
  }

  if (contract.maxBytes) {
    const contentBytes = Buffer.byteLength(rootContent, 'utf8');
    if (contentBytes > contract.maxBytes) {
      issues.push({
        code: 'too-large',
        message: `Root document exceeds byte budget (${contentBytes} bytes, expected at most ${contract.maxBytes}).`,
        reference: String(contentBytes),
      });
    }
  }

  for (const heading of contract.requiredHeadings) {
    if (!hasHeading(rootContent, heading)) {
      issues.push({
        code: 'missing-heading',
        message: `Missing required heading "${heading}".`,
        reference: heading,
      });
    }
  }

  const prerequisitesSection = getSectionContent(rootContent, 'Prerequisites');
  if (prerequisitesSection && prerequisitesSection.length > 0) {
    const installPattern =
      /\b(?:npm\s+install|npm\s+i|pnpm\s+install|yarn(?:\s+install)?|bun\s+install)\b/i;
    if (!installPattern.test(prerequisitesSection)) {
      issues.push({
        code: 'missing-prerequisite-step',
        message: 'Prerequisites section does not include dependency installation command.',
        reference: 'install-command',
      });
    }
  }

  const scriptNames = Object.keys(scripts);
  const minimumCommands = Math.min(contract.minCommandMentions, scriptNames.length);
  if (minimumCommands > 0) {
    const commandMentions = countCommandMentions(rootContent, scriptNames);
    if (commandMentions < minimumCommands) {
      issues.push({
        code: 'low-command-coverage',
        message: `Root document references too few executable project commands (${commandMentions}/${minimumCommands}).`,
        reference: `${commandMentions}/${minimumCommands}`,
      });
    }
  }

  for (const warningTopic of contract.requiredWarningTopics) {
    const topicPattern = getWarningTopicPattern(warningTopic);
    if (!topicPattern.test(rootContent)) {
      issues.push({
        code: 'missing-warning-topic',
        message: `Critical warning topic is missing: ${warningTopic}.`,
        reference: warningTopic,
      });
    }
  }

  const missingDetailedLinks = getMissingDetailedDocLinks(rootContent, target);
  if (missingDetailedLinks.length > 0) {
    issues.push({
      code: 'missing-detailed-doc-links',
      message: `Root document is missing canonical detailed-doc links: ${missingDetailedLinks.join(', ')}.`,
      reference: missingDetailedLinks.join(', '),
    });
  }

  if (riskSignals.tokenStorageLocalStorage) {
    const tokenPattern = /\b(localstorage|token storage|auth token|session token)\b/i;
    if (!tokenPattern.test(rootContent)) {
      issues.push({
        code: 'missing-risk-signal',
        message: 'Root document does not mention localStorage token risk.',
        reference: 'localStorage token handling',
      });
    }
  }

  if (riskSignals.apiMockCoverageGaps.length > 0) {
    const apiMockPattern = /\b(api\/mock gap|mock coverage gap|endpoint coverage mismatch)\b/i;
    if (!apiMockPattern.test(rootContent)) {
      issues.push({
        code: 'missing-risk-signal',
        message: 'Root document does not mention API/mock coverage gaps.',
        reference: 'API/mock coverage gaps',
      });
    }
  }

  if (riskSignals.toolingDependencyGaps.length > 0) {
    const toolingPattern = /\b(prerequisite|dependency gap|tooling mismatch|eslint config)\b/i;
    if (!toolingPattern.test(rootContent)) {
      issues.push({
        code: 'missing-risk-signal',
        message: 'Root document does not mention tooling dependency gaps/prerequisites.',
        reference: 'tooling dependency gaps',
      });
    }
  }

  if (riskSignals.strictTypeScriptFlags.length > 0) {
    const tsGatePattern = /\b(typescript gate|strict typecheck|compiler gate|noUnused)\b/i;
    if (!tsGatePattern.test(rootContent)) {
      issues.push({
        code: 'missing-risk-signal',
        message: 'Root document does not mention strict TypeScript gates.',
        reference: 'TypeScript strict gates',
      });
    }
  }

  return issues;
}

export function summarizeRootQualityIssues(issues: RootQualityIssue[]): string {
  if (issues.length === 0) return 'none';
  return issues
    .slice(0, 8)
    .map((issue) => `${issue.code}: ${issue.reference}`)
    .join('; ');
}

export function getRequiredRiskSignalLabels(riskSignals: FactPackRiskSignals): string[] {
  return summarizeRiskSignals(riskSignals);
}

export function getBlockingRootQualityIssues(issues: RootQualityIssue[]): RootQualityIssue[] {
  return issues.filter((issue) => BLOCKING_ROOT_ISSUE_CODES.has(issue.code));
}

export function getAdvisoryRootQualityIssues(issues: RootQualityIssue[]): RootQualityIssue[] {
  return issues.filter((issue) => !BLOCKING_ROOT_ISSUE_CODES.has(issue.code));
}
