import fs from 'node:fs/promises';
import path from 'node:path';
import type {
  ProjectConfig,
  Target,
  ValidationChecklistItem,
  ValidationIssue,
  ValidationResult,
  ValidationScoreBand,
  ValidationScoreCriterion,
  ValidationScoreCriterionKey,
  ValidationScoreReport,
} from '../types/index.js';
import { fileExists, readFileSafe, readJsonSafe } from '../utils/fs.js';
import { normalizeTargets } from '../utils/targets.js';
import { getCursorCanonicalDocLinks, getRootDocContract } from './docs-contract.js';
import { readDocsManifest } from './docs-manifest.js';
import { buildManagedFilesForTargets, resolveOutputLayout } from './output-layout.js';
import { collectProjectFacts } from './project-facts.js';
import { getFirstDifferentParityLine, rootsMatchUnderParityRules } from './root-parity.js';

const COMMAND_PREFIXES = ['npm', 'yarn', 'pnpm', 'npx', 'bun', 'make', 'node', 'tsx', 'ts-node'];
const PATH_PATTERN = /(?:^|\s)(\.?\.?\/[\w./-]+|\w+\/[\w./-]+)/g;
const CODE_BLOCK_PATTERN = /```[\s\S]*?```/g;
const INLINE_CODE_PATTERN = /`([^`]+)`/g;
const MARKDOWN_LINK_PATTERN = /\[[^\]]+\]\(([^)]+)\)/g;
const GENERATED_CLAUDE_DOCS = new Set([
  'architecture.md',
  'commands.md',
  'coding-style.md',
  'testing.md',
]);
const SHARED_ROOT_DOCS = ['CLAUDE.md', 'AGENTS.md'];
const ROOT_DOC_PATHS = ['CLAUDE.md', 'AGENTS.md', '.cursor/rules/project.mdc'];
const CURSOR_ADAPTER_DOC_MAX_NON_EMPTY_LINES = 90;
const CURSOR_ROOT_DOC_MAX_NON_EMPTY_LINES = 140;
const CURSOR_OVERLAP_WARNING_THRESHOLD = 0.45;
const CURSOR_OVERLAP_MIN_SHARED_LINES = 15;
const CURSOR_OVERLAP_MIN_CURSOR_LINES = 20;
const CURSOR_ALLOWED_ROOT_HEADINGS = new Set([
  'overview',
  'key commands',
  'quality gates',
  'critical warnings',
  'detailed docs',
]);
const CURSOR_ALLOWED_ADAPTER_HEADINGS: Record<string, Set<string>> = {
  'architecture.mdc': new Set(['canonical source', 'cursor focus', 'verify']),
  'style.mdc': new Set(['canonical source', 'cursor focus', 'verify']),
  'testing.mdc': new Set(['canonical source', 'cursor focus', 'verify']),
  'guardrails.mdc': new Set(['canonical source', 'cursor focus', 'handoff checklist']),
};
const WARNING_TOPIC_PATTERNS: Record<string, RegExp> = {
  secrets: /\b(secret(?:s)?|api[_ -]?key|credential|token)\b/i,
  'generated files':
    /\b(generated|do not edit|autogenerated|mockserviceworker|llmdocs\.evidence\.json)\b/i,
  'breaking changes': /\b(breaking|migration|compatibility|invariant)\b/i,
  'validation before handoff': /\b(validate|typecheck|lint|test|quality gate)\b/i,
  'localstorage token handling': /\b(localstorage|token storage|auth token|session token)\b/i,
};

const QUALITY_GATE_PATTERNS: Record<string, RegExp> = {
  build: /\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?build\b|\bbuild\b/i,
  lint: /\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?lint\b|\blint\b/i,
  typecheck: /\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?typecheck\b|\btype\s*check\b|\btsc\b/i,
  test: /\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?test\b|\btest\b/i,
  preview: /\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?preview\b|\bpreview\b/i,
};
const OPTIONAL_GATE_PATTERN = /\b(optional|if needed|when needed|if applicable|if available)\b/i;

const CONSISTENCY_WARNING_TOPICS = new Set<string>(
  Array.from(
    new Set([
      ...getRootDocContract('claude').requiredWarningTopics,
      ...getRootDocContract('codex').requiredWarningTopics,
      ...getRootDocContract('cursor').requiredWarningTopics,
    ]),
  ),
);

const ABSOLUTE_FILESYSTEM_PREFIXES = [
  '/Users/',
  '/home/',
  '/tmp/',
  '/var/',
  '/opt/',
  '/etc/',
  '/usr/',
  '/bin/',
  '/sbin/',
  '/src/',
  '/tests/',
  '/.claude/',
  '/.cursor/',
];

const FACTUAL_DOC_PATHS = [
  'CLAUDE.md',
  'AGENTS.md',
  '.cursor/rules/project.mdc',
  '.claude/docs/architecture.md',
  '.cursor/rules/architecture.mdc',
];
const CORE_PARITY_SCRIPTS = ['build', 'test', 'lint', 'typecheck', 'dev', 'preview', 'start'];
const ISSUE_SEVERITY_MULTIPLIER: Record<ValidationIssue['type'], number> = {
  'missing-command': 1,
  'missing-path': 0.65,
  'stale-reference': 0.65,
  'invalid-root-structure': 1,
  'missing-critical-warning': 0.65,
  'target-inconsistency': 0.65,
  'inconsistent-quality-gate': 0.65,
  'low-information-density': 0.65,
};

const RUBRIC_CRITERIA: Array<{
  key: ValidationScoreCriterionKey;
  label: string;
  weight: number;
}> = [
  { key: 'accuracy', label: 'Accuracy', weight: 25 },
  { key: 'actionability', label: 'Actionability', weight: 20 },
  { key: 'crossTargetConsistency', label: 'Cross-target consistency', weight: 15 },
  { key: 'safetyCoverage', label: 'Safety coverage', weight: 15 },
  { key: 'maintainability', label: 'Maintainability', weight: 15 },
  { key: 'driftResistance', label: 'Drift resistance', weight: 10 },
];

const RUBRIC_PENALTY_RULES: Record<
  ValidationScoreCriterionKey,
  Partial<Record<ValidationIssue['type'], number>>
> = {
  accuracy: {
    'missing-command': 2.2,
    'missing-path': 1.6,
    'stale-reference': 1.4,
    'invalid-root-structure': 0.8,
    'target-inconsistency': 1.6,
  },
  actionability: {
    'missing-command': 1.3,
    'inconsistent-quality-gate': 1.2,
    'low-information-density': 1.6,
    'invalid-root-structure': 1.1,
  },
  crossTargetConsistency: {
    'target-inconsistency': 2,
    'inconsistent-quality-gate': 1.6,
  },
  safetyCoverage: {
    'missing-critical-warning': 2,
    'target-inconsistency': 0.9,
    'invalid-root-structure': 0.5,
  },
  maintainability: {
    'low-information-density': 1.9,
    'missing-path': 1,
    'invalid-root-structure': 1.2,
    'stale-reference': 0.8,
  },
  driftResistance: {
    'target-inconsistency': 1.8,
    'inconsistent-quality-gate': 1.2,
    'missing-path': 0.8,
    'stale-reference': 0.8,
    'missing-command': 0.9,
  },
};

function getRootTarget(filePath: string): 'claude' | 'codex' | 'cursor' | null {
  const normalized = filePath.replace(/\\/g, '/');
  if (normalized.endsWith('CLAUDE.md')) return 'claude';
  if (normalized.endsWith('AGENTS.md')) return 'codex';
  if (normalized.endsWith('.cursor/rules/project.mdc')) return 'cursor';
  return null;
}

function normalizeConfiguredTargets(rawTargets: unknown): Target[] {
  if (!Array.isArray(rawTargets)) return [];
  const values = rawTargets.map((target) => String(target));
  try {
    return normalizeTargets(values, 'llmdocs.config.json targets');
  } catch {
    return [];
  }
}

function getSectionContent(content: string, heading: string): string | null {
  const headingMatch = new RegExp(`^#{1,6}\\s*${heading}\\s*:?\\s*$`, 'im').exec(content);
  if (!headingMatch || headingMatch.index === undefined) {
    return null;
  }

  const fromHeading = content.slice(headingMatch.index + headingMatch[0].length);
  const nextHeadingIndex = fromHeading.search(/\n#{1,6}\s+/);
  if (nextHeadingIndex < 0) {
    return fromHeading.trim();
  }
  return fromHeading.slice(0, nextHeadingIndex).trim();
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function extractCursorFrontmatter(content: string): string | null {
  const normalized = content.replace(/\r\n/g, '\n');
  const match = normalized.match(/^---\s*\n([\s\S]*?)\n---\s*(?:\n|$)/);
  return match?.[1] ?? null;
}

function extractFrontmatterField(frontmatter: string, fieldName: string): string | null {
  const fieldPattern = new RegExp(`^\\s*${escapeRegExp(fieldName)}\\s*:(.*)$`, 'i');
  for (const line of frontmatter.split('\n')) {
    const match = line.match(fieldPattern);
    if (!match) continue;
    return (match[1] ?? '').trim();
  }
  return null;
}

function hasNonEmptyGlobValue(globsValue: string | null): boolean {
  if (!globsValue) return false;
  const normalized = globsValue.replace(/['"`]/g, '').trim();
  if (!normalized) return false;
  if (normalized === '[]') return false;
  return true;
}

function stripLeadingFrontmatter(content: string): string {
  const normalized = content.replace(/\r\n/g, '\n');
  const match = normalized.match(/^---\s*\n[\s\S]*?\n---\s*(?:\n|$)/);
  if (!match) return normalized;
  return normalized.slice(match[0].length);
}

function countNonEmptyLines(content: string): number {
  return content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0).length;
}

function isCursorRuleFile(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, '/');
  return normalized.includes('/.cursor/rules/') && normalized.endsWith('.mdc');
}

function getCursorRuleFilename(filePath: string): string {
  return path.posix.basename(filePath.replace(/\\/g, '/'));
}

function normalizeHeadingLabel(value: string): string {
  return value
    .replace(/[`*_]/g, '')
    .replace(/\s*:+\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function extractHeadingsByLevel(content: string, level: number): string[] {
  const pattern = new RegExp(`^#{${level}}\\s+(.+)$`, 'gim');
  return Array.from(content.matchAll(pattern))
    .map((match) => match[1]?.trim() ?? '')
    .filter((value) => value.length > 0);
}

function getUnsupportedCursorRuleHeadings(content: string, ruleFilename: string): string[] {
  const body = stripLeadingFrontmatter(content);
  const headings = extractHeadingsByLevel(body, 2).map(normalizeHeadingLabel);
  if (headings.length === 0) {
    return [];
  }

  const allowedHeadings =
    ruleFilename === 'project.mdc'
      ? CURSOR_ALLOWED_ROOT_HEADINGS
      : CURSOR_ALLOWED_ADAPTER_HEADINGS[ruleFilename];
  if (!allowedHeadings) {
    return [];
  }

  return headings.filter((heading) => !allowedHeadings.has(heading));
}

function hasCursorCanonicalSourceLink(content: string, ruleFilename: string): boolean {
  const links = getCursorCanonicalDocLinks(ruleFilename);
  if (links.length === 0) {
    return /\.claude\/docs\/[a-z0-9._/-]+\.md/i.test(content);
  }
  const normalized = content.toLowerCase();
  return links.some((link) => normalized.includes(link.toLowerCase()));
}

function hasDuplicateFrontmatterBlockInBody(content: string): boolean {
  const body = stripLeadingFrontmatter(content);
  const yamlFencePattern = /```ya?ml[\t ]*\n[\s\S]*?```/gi;
  for (const match of body.matchAll(yamlFencePattern)) {
    if (/\b(?:description|globs|alwaysApply)\s*:/i.test(match[0] ?? '')) {
      return true;
    }
  }

  const inlineFrontmatterPattern = /(?:^|\n)---\s*\n([\s\S]*?)\n---\s*(?=\n|$)/g;
  for (const match of body.matchAll(inlineFrontmatterPattern)) {
    if (/\b(?:description|globs|alwaysApply)\s*:/i.test(match[1] ?? '')) {
      return true;
    }
  }

  return false;
}

function normalizeLineForOverlap(value: string): string {
  return value
    .replace(/\[[^\]]+\]\(([^)]+)\)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/^[-*]\s+/, '')
    .replace(/^#{1,6}\s+/, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function buildComparableLineSet(content: string): Set<string> {
  const body = stripLeadingFrontmatter(content);
  const lines = body
    .split('\n')
    .map(normalizeLineForOverlap)
    .filter((line) => line.length >= 14);
  return new Set(lines);
}

function getCriticalWarningsSection(content: string): string | null {
  return getSectionContent(content, 'Critical Warnings');
}

function getQualityGatesSection(content: string): string | null {
  return getSectionContent(content, 'Quality Gates');
}

function detectWarningTopics(content: string): Set<string> {
  const topics = new Set<string>();
  for (const [topic, pattern] of Object.entries(WARNING_TOPIC_PATTERNS)) {
    if (pattern.test(content)) {
      topics.add(topic);
    }
  }
  return topics;
}

function detectQualityGateStatuses(section: string): Map<string, 'required' | 'optional'> {
  const statuses = new Map<string, 'required' | 'optional'>();
  const lines = section
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  for (const line of lines) {
    const optional = OPTIONAL_GATE_PATTERN.test(line);
    for (const [gate, pattern] of Object.entries(QUALITY_GATE_PATTERNS)) {
      if (!pattern.test(line)) continue;
      const previous = statuses.get(gate);
      const next: 'required' | 'optional' = optional ? 'optional' : 'required';
      if (!previous || previous === 'optional') {
        statuses.set(gate, next);
      }
      if (previous === 'required' && next === 'optional') {
        statuses.set(gate, 'required');
      }
    }
  }

  return statuses;
}

function clampScore(value: number): number {
  if (!Number.isFinite(value)) return 0;
  if (value < 0) return 0;
  if (value > 10) return 10;
  return value;
}

function roundScore(value: number): number {
  return Math.round(value * 10) / 10;
}

function getRubricBand(overall: number): ValidationScoreBand {
  if (overall < 4) return 'fail';
  if (overall < 7) return 'acceptable';
  if (overall < 9) return 'good';
  return 'excellent';
}

function countIssuesByType(issues: ValidationIssue[]): Map<ValidationIssue['type'], number> {
  const counts = new Map<ValidationIssue['type'], number>();
  for (const issue of issues) {
    counts.set(issue.type, (counts.get(issue.type) ?? 0) + 1);
  }
  return counts;
}

function buildCriterionScore(
  key: ValidationScoreCriterionKey,
  issueCounts: Map<ValidationIssue['type'], number>,
): number {
  const penaltyRules = RUBRIC_PENALTY_RULES[key];
  let deduction = 0;

  for (const [issueType, count] of issueCounts.entries()) {
    const penaltyWeight = penaltyRules[issueType];
    if (!penaltyWeight || count <= 0) continue;
    const severityMultiplier = ISSUE_SEVERITY_MULTIPLIER[issueType] ?? 0.65;
    deduction += penaltyWeight * Math.log2(1 + count) * severityMultiplier;
  }

  return roundScore(clampScore(10 - deduction));
}

function hasIssueByType(issues: ValidationIssue[], type: ValidationIssue['type']): boolean {
  return issues.some((issue) => issue.type === type);
}

function hasIssueByReferencePrefix(issues: ValidationIssue[], prefix: string): boolean {
  return issues.some((issue) => issue.reference.startsWith(prefix));
}

function hasIssueByReference(issues: ValidationIssue[], reference: string): boolean {
  return issues.some((issue) => issue.reference === reference);
}

function hasRootSizeIssue(issues: ValidationIssue[]): boolean {
  return issues.some(
    (issue) =>
      issue.type === 'low-information-density' &&
      (issue.message.includes('too long') || issue.message.includes('byte budget')),
  );
}

function toChecklistStatus(
  evaluated: boolean,
  passing: boolean,
): ValidationChecklistItem['status'] {
  if (!evaluated) return 'unknown';
  return passing ? 'pass' : 'fail';
}

function buildValidationChecklist(
  issues: ValidationIssue[],
  context: {
    hasRootDocs: boolean;
    hasMultipleRoots: boolean;
    hasCursorRules: boolean;
  },
): ValidationChecklistItem[] {
  const commandParityDrift =
    hasIssueByReferencePrefix(issues, 'command-parity:') ||
    hasIssueByReference(issues, 'root-parity');
  const qualityGateDrift = hasIssueByType(issues, 'inconsistent-quality-gate');
  const criticalWarningsMissing = hasIssueByType(issues, 'missing-critical-warning');
  const cursorFrontmatterIssues = hasIssueByReferencePrefix(issues, 'cursor-frontmatter');

  return [
    {
      id: 'commands_exist',
      label: 'All documented commands exist in package scripts',
      status: toChecklistStatus(true, !hasIssueByType(issues, 'missing-command')),
      details: 'Based on missing-command validation issues.',
    },
    {
      id: 'command_parity',
      label: 'Core commands are consistent across root docs',
      status: toChecklistStatus(context.hasMultipleRoots, !commandParityDrift),
      details: context.hasMultipleRoots
        ? 'Checks cross-target command parity and CLAUDE/AGENTS root parity.'
        : 'Needs at least two root docs.',
    },
    {
      id: 'root_size_budget',
      label: 'Root docs are within configured size budgets',
      status: toChecklistStatus(context.hasRootDocs, !hasRootSizeIssue(issues)),
      details: context.hasRootDocs
        ? 'Checks max lines/bytes constraints from root contract.'
        : 'No root docs found to evaluate.',
    },
    {
      id: 'security_boundaries',
      label: 'Critical warnings and safety boundaries are present',
      status: toChecklistStatus(context.hasRootDocs, !criticalWarningsMissing),
      details: context.hasRootDocs
        ? 'Checks required warning topics in Critical Warnings section.'
        : 'No root docs found to evaluate.',
    },
    {
      id: 'path_references',
      label: 'Documented file paths resolve in repository',
      status: toChecklistStatus(true, !hasIssueByType(issues, 'missing-path')),
      details: 'Based on markdown-link and inline-path resolution checks.',
    },
    {
      id: 'quality_gate_consistency',
      label: 'Quality gate policy is consistent across targets',
      status: toChecklistStatus(context.hasMultipleRoots, !qualityGateDrift),
      details: context.hasMultipleRoots
        ? 'Checks required/optional gate drift across root docs.'
        : 'Needs at least two root docs.',
    },
    {
      id: 'factual_drift',
      label: 'No factual drift against project code signals',
      status: toChecklistStatus(true, !hasIssueByType(issues, 'target-inconsistency')),
      details: 'Compares docs claims with detected routes/APIs/tooling facts.',
    },
    {
      id: 'cursor_frontmatter',
      label: 'Cursor .mdc files have valid frontmatter',
      status: toChecklistStatus(context.hasCursorRules, !cursorFrontmatterIssues),
      details: context.hasCursorRules
        ? 'Validates description/globs/alwaysApply contract.'
        : 'No Cursor rules found to evaluate.',
    },
  ];
}

function buildValidationScoreReport(
  issues: ValidationIssue[],
  context: {
    hasRootDocs: boolean;
    hasMultipleRoots: boolean;
    hasCursorRules: boolean;
  },
): ValidationScoreReport {
  const issueCounts = countIssuesByType(issues);
  const criteria: ValidationScoreCriterion[] = RUBRIC_CRITERIA.map((criterion) => ({
    key: criterion.key,
    label: criterion.label,
    weight: criterion.weight,
    score: buildCriterionScore(criterion.key, issueCounts),
  }));

  const weightSum = criteria.reduce((sum, criterion) => sum + criterion.weight, 0) || 1;
  const weightedScore =
    criteria.reduce((sum, criterion) => sum + criterion.score * criterion.weight, 0) / weightSum;
  const overall = roundScore(weightedScore);

  return {
    overall,
    band: getRubricBand(overall),
    criteria,
    checklist: buildValidationChecklist(issues, context),
  };
}

function validateRootStructure(filePath: string, content: string): ValidationIssue[] {
  const target = getRootTarget(filePath);
  if (!target) return [];

  const issues: ValidationIssue[] = [];
  const contract = getRootDocContract(target);
  const nonEmptyLines = content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  for (const heading of contract.requiredHeadings) {
    const headingRegex = new RegExp(`^\\s*#{1,6}\\s*${heading}\\s*:?\\s*$`, 'im');
    if (!headingRegex.test(content)) {
      issues.push({
        file: filePath,
        line: 1,
        type: 'invalid-root-structure',
        message: `Missing required heading "${heading}" in root document.`,
        reference: heading,
      });
    }
  }

  for (const disallowedPattern of contract.disallowedPatterns) {
    if (disallowedPattern.test(content)) {
      issues.push({
        file: filePath,
        line: 1,
        type: 'invalid-root-structure',
        message: 'Root document contains generation/process-log style text.',
        reference: disallowedPattern.source,
      });
    }
  }

  if (nonEmptyLines.length < contract.minNonEmptyLines) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'low-information-density',
      message: `Root document is too short (${nonEmptyLines.length} lines, expected at least ${contract.minNonEmptyLines}).`,
      reference: String(nonEmptyLines.length),
    });
  }

  if (contract.maxNonEmptyLines && nonEmptyLines.length > contract.maxNonEmptyLines) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'low-information-density',
      message: `Root document is too long (${nonEmptyLines.length} lines, expected at most ${contract.maxNonEmptyLines}).`,
      reference: String(nonEmptyLines.length),
    });
  }

  if (contract.maxBytes) {
    const contentBytes = Buffer.byteLength(content, 'utf8');
    if (contentBytes > contract.maxBytes) {
      issues.push({
        file: filePath,
        line: 1,
        type: 'low-information-density',
        message: `Root document exceeds byte budget (${contentBytes} bytes, expected at most ${contract.maxBytes}).`,
        reference: String(contentBytes),
      });
    }
  }

  const warningSection = getCriticalWarningsSection(content);
  if (!warningSection) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'missing-critical-warning',
      message: 'Missing "Critical Warnings" section in root document.',
      reference: 'Critical Warnings',
    });
    return issues;
  }

  const warningTopics = detectWarningTopics(warningSection);
  for (const requiredTopic of contract.requiredWarningTopics) {
    if (!warningTopics.has(requiredTopic)) {
      issues.push({
        file: filePath,
        line: 1,
        type: 'missing-critical-warning',
        message: `Missing warning topic "${requiredTopic}" in Critical Warnings section.`,
        reference: requiredTopic,
      });
    }
  }

  return issues;
}

function validateCursorFrontmatter(filePath: string, content: string): ValidationIssue[] {
  if (!filePath.replace(/\\/g, '/').endsWith('.mdc')) {
    return [];
  }

  const issues: ValidationIssue[] = [];
  const frontmatter = extractCursorFrontmatter(content);
  if (!frontmatter) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message:
        'Cursor rule file is missing YAML frontmatter. Add description/globs/alwaysApply fields.',
      reference: 'cursor-frontmatter',
    });
    return issues;
  }

  const descriptionValue = extractFrontmatterField(frontmatter, 'description');
  const globsValue = extractFrontmatterField(frontmatter, 'globs');
  const alwaysApplyValue = extractFrontmatterField(frontmatter, 'alwaysApply');

  if (descriptionValue === null) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message: 'Cursor frontmatter must include "description".',
      reference: 'cursor-frontmatter:description',
    });
  }

  if (globsValue === null) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message: 'Cursor frontmatter must include "globs".',
      reference: 'cursor-frontmatter:globs',
    });
  }

  if (alwaysApplyValue === null) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message: 'Cursor frontmatter must include "alwaysApply".',
      reference: 'cursor-frontmatter:alwaysApply',
    });
    return issues;
  }

  const normalizedAlwaysApply = alwaysApplyValue.toLowerCase();
  if (normalizedAlwaysApply !== 'true' && normalizedAlwaysApply !== 'false') {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message: 'Cursor frontmatter "alwaysApply" must be a boolean (true/false).',
      reference: `cursor-frontmatter:alwaysApply=${alwaysApplyValue}`,
    });
    return issues;
  }

  const alwaysApply = normalizedAlwaysApply === 'true';
  if (alwaysApply && hasNonEmptyGlobValue(globsValue)) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message: 'Cursor rule with alwaysApply=true must keep globs empty.',
      reference: 'cursor-frontmatter:alwaysApply+globs',
    });
  }

  const normalizedPath = filePath.replace(/\\/g, '/');
  if (normalizedPath.endsWith('/.cursor/rules/project.mdc') && !alwaysApply) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message: 'project.mdc must be always-on (alwaysApply: true).',
      reference: 'cursor-frontmatter:project-alwaysApply',
    });
  }

  return issues;
}

function validateCursorRuleAdapterQuality(filePath: string, content: string): ValidationIssue[] {
  if (!isCursorRuleFile(filePath)) {
    return [];
  }

  const issues: ValidationIssue[] = [];
  const ruleFilename = getCursorRuleFilename(filePath);
  const nonEmptyLines = countNonEmptyLines(stripLeadingFrontmatter(content));
  const maxLines =
    ruleFilename === 'project.mdc'
      ? CURSOR_ROOT_DOC_MAX_NON_EMPTY_LINES
      : CURSOR_ADAPTER_DOC_MAX_NON_EMPTY_LINES;

  if (nonEmptyLines > maxLines) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'low-information-density',
      message: `Cursor rule "${ruleFilename}" is too long for a scoped adapter (${nonEmptyLines} lines, expected at most ${maxLines}).`,
      reference: `cursor-rule-size:${ruleFilename}`,
    });
  }

  if (ruleFilename !== 'project.mdc' && !hasCursorCanonicalSourceLink(content, ruleFilename)) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'target-inconsistency',
      message: `Cursor adapter "${ruleFilename}" is missing link(s) to canonical shared docs under .claude/docs/.`,
      reference: `cursor-adapter:canonical-link:${ruleFilename}`,
    });
  }

  if (hasDuplicateFrontmatterBlockInBody(content)) {
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message:
        'Cursor rule body must not duplicate frontmatter blocks. Keep description/globs/alwaysApply only in the leading YAML frontmatter.',
      reference: `cursor-frontmatter:body-duplicate:${ruleFilename}`,
    });
  }

  const unsupportedHeadings = getUnsupportedCursorRuleHeadings(content, ruleFilename);
  if (unsupportedHeadings.length > 0) {
    const sample = unsupportedHeadings.slice(0, 3).join(', ');
    issues.push({
      file: filePath,
      line: 1,
      type: 'invalid-root-structure',
      message: `Cursor rule "${ruleFilename}" contains unsupported section headings for a thin adapter: ${sample}.`,
      reference:
        ruleFilename === 'project.mdc'
          ? `cursor-root:unsupported-heading:${sample}`
          : `cursor-adapter:unsupported-heading:${ruleFilename}:${sample}`,
    });
  }

  return issues;
}

async function readRootDocs(projectRoot: string): Promise<Map<string, string>> {
  const docs = new Map<string, string>();
  for (const relativePath of ROOT_DOC_PATHS) {
    const fullPath = path.join(projectRoot, relativePath);
    const content = await readFileSafe(fullPath);
    if (content) {
      docs.set(relativePath, content);
    }
  }
  return docs;
}

function hasRegisterEvidence(routePaths: string[], authApiFunctions: string[]): boolean {
  return (
    routePaths.some((route) => /\b(register|sign-up|signup)\b/i.test(route)) ||
    authApiFunctions.some((fn) => /\b(register|signUp|signup)\b/i.test(fn))
  );
}

function detectNoAnyHardClaim(content: string): boolean {
  return (
    /\bany\s+type\s+is\s+strictly\s+prohibited\b/i.test(content) ||
    /\bnever\s+use\s+`?any`?\b/i.test(content) ||
    /\bno\s+`?any`?\s+type\b/i.test(content)
  );
}

function detectNoTestFrameworkClaim(content: string): boolean {
  return (
    /\bno test framework\b/i.test(content) ||
    /\bno test runner\b/i.test(content) ||
    /\bno automated tests\b/i.test(content) ||
    /\bthere is no `?npm run test`?\b/i.test(content)
  );
}

function detectAuthRouteClaim(content: string): string | null {
  const architectureSection = getSectionContent(content, 'Architecture Snapshot') ?? content;
  const match = architectureSection.match(/\/auth(?:\/\*|\/[a-z0-9_-]+|\b)/i);
  return match?.[0] ?? null;
}

function detectMentionedTokenPath(content: string): string | null {
  const normalized = content.toLowerCase();
  if (normalized.includes('src/api/auth.ts')) {
    return 'src/api/auth.ts';
  }
  return null;
}

function detectJsonServerMention(content: string): boolean {
  return /\bjson-server\b/i.test(content);
}

async function validateDocsAgainstProjectFacts(projectRoot: string): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const pkg = await readJsonSafe<Record<string, unknown>>(path.join(projectRoot, 'package.json'));
  const projectFacts = await collectProjectFacts(projectRoot, pkg);

  const routesWithAuthPrefix = projectFacts.routePaths.filter((route) => route.startsWith('/auth'));
  const registerEvidence = hasRegisterEvidence(
    projectFacts.routePaths,
    projectFacts.authApiFunctions,
  );
  const authRouteEvidenceExists = routesWithAuthPrefix.length > 0;
  const hasJsonServerScriptEvidence = projectFacts.jsonServerScriptNames.length > 0;
  const hasAnyUsageEvidence = projectFacts.anyTypeUsageFiles.length > 0;
  const tokenStorageWriteFiles = new Set(projectFacts.tokenStorageWriteFiles);

  for (const relativePath of FACTUAL_DOC_PATHS) {
    const fullPath = path.join(projectRoot, relativePath);
    const content = await readFileSafe(fullPath);
    if (!content) continue;

    if (!registerEvidence && /\bregister(?:ed|ation)?\b/i.test(content)) {
      issues.push({
        file: fullPath,
        line: 1,
        type: 'target-inconsistency',
        message:
          'Documentation claims register/registration behavior, but no register route/function was detected in source.',
        reference: 'register',
      });
    }

    const authRouteClaim = detectAuthRouteClaim(content);
    if (authRouteClaim && !authRouteEvidenceExists) {
      issues.push({
        file: fullPath,
        line: 1,
        type: 'target-inconsistency',
        message:
          'Documentation describes /auth route paths, but router files do not contain /auth routes.',
        reference: authRouteClaim,
      });
    }

    if (detectJsonServerMention(content) && !hasJsonServerScriptEvidence) {
      issues.push({
        file: fullPath,
        line: 1,
        type: 'target-inconsistency',
        message:
          'Documentation mentions json-server runtime usage, but no json-server script is configured.',
        reference: 'json-server',
      });
    }

    if (
      detectNoAnyHardClaim(content) &&
      hasAnyUsageEvidence &&
      !projectFacts.eslintNoExplicitAnyRuleConfigured
    ) {
      issues.push({
        file: fullPath,
        line: 1,
        type: 'target-inconsistency',
        message:
          'Documentation states strict no-any enforcement, but source contains any-typed code and no explicit no-explicit-any rule is configured.',
        reference: 'any-policy',
      });
    }

    const mentionedTokenPath = detectMentionedTokenPath(content);
    if (
      mentionedTokenPath &&
      tokenStorageWriteFiles.size > 0 &&
      !tokenStorageWriteFiles.has(mentionedTokenPath)
    ) {
      issues.push({
        file: fullPath,
        line: 1,
        type: 'target-inconsistency',
        message:
          'Token storage location in docs does not match detected localStorage write location in source.',
        reference: `${mentionedTokenPath} != ${Array.from(tokenStorageWriteFiles).join(', ')}`,
      });
    }
  }

  return issues;
}

function pushMixedRootFactIssues(
  issues: ValidationIssue[],
  projectRoot: string,
  label: string,
  valuesByDoc: Map<string, boolean>,
): void {
  if (valuesByDoc.size < 2) return;
  const distinctValues = new Set(valuesByDoc.values());
  if (distinctValues.size <= 1) return;

  for (const [docPath, value] of valuesByDoc.entries()) {
    issues.push({
      file: path.join(projectRoot, docPath),
      line: 1,
      type: 'target-inconsistency',
      message: `Cross-target factual drift detected for "${label}" (${value ? 'mentioned' : 'missing'}).`,
      reference: `${label}:${value ? 'mentioned' : 'missing'}`,
    });
  }
}

async function validateCrossTargetFactConsistency(
  projectRoot: string,
  scripts: Record<string, string>,
): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const rootDocs = await readRootDocs(projectRoot);
  if (rootDocs.size < 2) return issues;

  const jsonServerByDoc = new Map<string, boolean>();
  const tokenPathByDoc = new Map<string, boolean>();
  const noTestsByDoc = new Map<string, boolean>();
  const expectNoTests = !scripts.test;

  for (const [docPath, content] of rootDocs.entries()) {
    jsonServerByDoc.set(docPath, detectJsonServerMention(content));
    tokenPathByDoc.set(docPath, /src\/api\/auth\.ts/i.test(content));
    if (expectNoTests) {
      noTestsByDoc.set(docPath, detectNoTestFrameworkClaim(content));
    }
  }

  pushMixedRootFactIssues(issues, projectRoot, 'json-server', jsonServerByDoc);
  pushMixedRootFactIssues(issues, projectRoot, 'token-storage-path', tokenPathByDoc);
  if (expectNoTests) {
    pushMixedRootFactIssues(issues, projectRoot, 'no-test-framework', noTestsByDoc);
  }

  return issues;
}

async function validateStaleManagedFiles(projectRoot: string): Promise<ValidationIssue[]> {
  const manifest = await readDocsManifest(projectRoot);
  if (!manifest || manifest.managedFiles.length === 0) {
    return [];
  }

  const config = await readJsonSafe<ProjectConfig>(path.join(projectRoot, 'llmdocs.config.json'));
  const configTargets = normalizeConfiguredTargets(config?.targets);
  const manifestTargets = normalizeConfiguredTargets(manifest.targets);
  const targets = configTargets.length > 0 ? configTargets : manifestTargets;
  if (targets.length === 0) {
    return [];
  }

  const layout = config ? resolveOutputLayout(config) : manifest.layout;
  const includeCanonicalForCursorOnly = targets.length === 1 && targets[0] === 'cursor';
  const expectedManaged = new Set(
    buildManagedFilesForTargets(targets, layout, {
      includeCanonicalForCursorOnly,
    }),
  );

  const issues: ValidationIssue[] = [];
  for (const managedPath of manifest.managedFiles) {
    if (expectedManaged.has(managedPath)) continue;
    const fullPath = path.join(projectRoot, managedPath);
    if (!(await fileExists(fullPath))) continue;

    issues.push({
      file: fullPath,
      line: 1,
      type: 'stale-reference',
      message:
        'Managed documentation file is stale for current config targets/layout. File was kept intentionally (auto-prune disabled).',
      reference: `stale-managed:${managedPath}`,
    });
  }

  return issues;
}

async function validateCursorCanonicalOverlap(projectRoot: string): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const cursorRulesDir = path.join(projectRoot, '.cursor', 'rules');

  let entries: string[] = [];
  try {
    entries = await fs.readdir(cursorRulesDir);
  } catch {
    return issues;
  }

  for (const entry of entries) {
    if (!entry.endsWith('.mdc') || entry === 'project.mdc') continue;

    const canonicalLinks = getCursorCanonicalDocLinks(entry);
    if (canonicalLinks.length === 0) continue;

    const cursorRulePath = path.join(cursorRulesDir, entry);
    const cursorContent = await readFileSafe(cursorRulePath);
    if (!cursorContent) continue;

    const cursorLines = buildComparableLineSet(cursorContent);
    if (cursorLines.size < CURSOR_OVERLAP_MIN_CURSOR_LINES) continue;

    for (const canonicalLink of canonicalLinks) {
      const canonicalPath = path.join(projectRoot, canonicalLink);
      const canonicalContent = await readFileSafe(canonicalPath);
      if (!canonicalContent) continue;

      const canonicalLines = buildComparableLineSet(canonicalContent);
      if (canonicalLines.size === 0) continue;

      let shared = 0;
      for (const line of cursorLines) {
        if (canonicalLines.has(line)) {
          shared += 1;
        }
      }

      const overlapRatio = shared / cursorLines.size;
      if (
        shared >= CURSOR_OVERLAP_MIN_SHARED_LINES &&
        overlapRatio >= CURSOR_OVERLAP_WARNING_THRESHOLD
      ) {
        issues.push({
          file: cursorRulePath,
          line: 1,
          type: 'target-inconsistency',
          message: `Cursor adapter "${entry}" overlaps too much with canonical doc "${canonicalLink}" (${Math.round(
            overlapRatio * 100,
          )}% shared lines). Keep cursor rules thin and scoped.`,
          reference: `cross-target-overlap:${entry}->${canonicalLink}`,
        });
      }
    }
  }

  return issues;
}

function detectScriptMentionsByRootDoc(
  content: string,
  scripts: Record<string, string>,
): Set<string> {
  const mentioned = new Set<string>();
  for (const scriptName of CORE_PARITY_SCRIPTS) {
    if (!scripts[scriptName]) continue;
    const escaped = escapeRegExp(scriptName);
    const pattern = new RegExp(
      `\\b(?:npm\\s+(?:run\\s+)?|pnpm\\s+|yarn\\s+|bun\\s+(?:run\\s+)?)${escaped}\\b`,
      'i',
    );
    if (pattern.test(content)) {
      mentioned.add(scriptName);
    }
  }
  return mentioned;
}

async function validateCrossTargetCommandParity(
  projectRoot: string,
  scripts: Record<string, string>,
): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const rootDocs = await readRootDocs(projectRoot);
  if (rootDocs.size < 2) return issues;

  const trackedScripts = CORE_PARITY_SCRIPTS.filter((scriptName) => scripts[scriptName]);
  if (trackedScripts.length === 0) return issues;

  const mentionsByDoc = new Map<string, Set<string>>();
  for (const [docPath, content] of rootDocs.entries()) {
    mentionsByDoc.set(docPath, detectScriptMentionsByRootDoc(content, scripts));
  }

  for (const scriptName of trackedScripts) {
    const statusByDoc = new Map<string, boolean>();
    for (const [docPath, mentions] of mentionsByDoc.entries()) {
      statusByDoc.set(docPath, mentions.has(scriptName));
    }

    const distinctStatuses = new Set(statusByDoc.values());
    if (distinctStatuses.size <= 1) continue;

    for (const [docPath, mentioned] of statusByDoc.entries()) {
      issues.push({
        file: path.join(projectRoot, docPath),
        line: 1,
        type: 'target-inconsistency',
        message: `Cross-target command drift detected for "${scriptName}" (${mentioned ? 'mentioned' : 'missing'}).`,
        reference: `command-parity:${scriptName}:${mentioned ? 'mentioned' : 'missing'}`,
      });
    }
  }

  return issues;
}

async function validateClaudeCodexRootParity(projectRoot: string): Promise<ValidationIssue[]> {
  const claudePath = path.join(projectRoot, 'CLAUDE.md');
  const codexPath = path.join(projectRoot, 'AGENTS.md');
  const claudeContent = await readFileSafe(claudePath);
  const codexContent = await readFileSafe(codexPath);

  if (!claudeContent || !codexContent) {
    return [];
  }

  if (rootsMatchUnderParityRules(claudeContent, codexContent)) {
    return [];
  }

  const line = getFirstDifferentParityLine(claudeContent, codexContent) ?? 1;
  return [
    {
      file: codexPath,
      line,
      type: 'target-inconsistency',
      message:
        'AGENTS.md drifted from CLAUDE.md. Keep root docs in parity except for the root filename heading.',
      reference: 'root-parity',
    },
  ];
}

async function validateRootDocsConsistency(projectRoot: string): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const rootTopicMap = new Map<string, Set<string>>();

  for (const relativePath of ROOT_DOC_PATHS) {
    const fullPath = path.join(projectRoot, relativePath);
    const content = await readFileSafe(fullPath);
    if (!content) continue;
    const section = getCriticalWarningsSection(content);
    if (!section) continue;
    rootTopicMap.set(relativePath, detectWarningTopics(section));
  }

  if (rootTopicMap.size < 2) {
    return issues;
  }

  for (const [docPath, topics] of rootTopicMap.entries()) {
    for (const topic of CONSISTENCY_WARNING_TOPICS) {
      if (!topics.has(topic)) {
        issues.push({
          file: path.join(projectRoot, docPath),
          line: 1,
          type: 'target-inconsistency',
          message: `Critical warning topic "${topic}" is present in other targets but missing here.`,
          reference: topic,
        });
      }
    }
  }

  return issues;
}

async function validateQualityGateConsistency(projectRoot: string): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const gateStatusByDoc = new Map<string, Map<string, 'required' | 'optional'>>();

  for (const relativePath of ROOT_DOC_PATHS) {
    const fullPath = path.join(projectRoot, relativePath);
    const content = await readFileSafe(fullPath);
    if (!content) continue;
    const section = getQualityGatesSection(content);
    if (!section) continue;
    gateStatusByDoc.set(relativePath, detectQualityGateStatuses(section));
  }

  if (gateStatusByDoc.size < 2) {
    return issues;
  }

  const allGates = new Set<string>();
  for (const statuses of gateStatusByDoc.values()) {
    for (const gate of statuses.keys()) {
      allGates.add(gate);
    }
  }

  for (const gate of allGates) {
    const statusesForGate: Array<{ docPath: string; status: 'required' | 'optional' }> = [];
    for (const [docPath, statuses] of gateStatusByDoc.entries()) {
      const status = statuses.get(gate);
      if (status) {
        statusesForGate.push({ docPath, status });
      }
    }

    const uniqueStatuses = new Set(statusesForGate.map((entry) => entry.status));
    if (uniqueStatuses.size <= 1) continue;

    for (const entry of statusesForGate) {
      issues.push({
        file: path.join(projectRoot, entry.docPath),
        line: 1,
        type: 'inconsistent-quality-gate',
        message: `Quality gate policy for "${gate}" is inconsistent across targets (${entry.status}).`,
        reference: `${gate}:${entry.status}`,
      });
    }
  }

  return issues;
}

function extractCommands(content: string): { line: number; command: string }[] {
  const results: { line: number; command: string }[] = [];
  const codeBlocks = content.matchAll(CODE_BLOCK_PATTERN);

  for (const match of codeBlocks) {
    const blockStart = content.slice(0, match.index).split('\n').length;
    const lines = match[0].split('\n').slice(1, -1);

    for (let i = 0; i < lines.length; i++) {
      const trimmed = lines[i].trim();
      if (COMMAND_PREFIXES.some((p) => trimmed.startsWith(p))) {
        results.push({ line: blockStart + i, command: trimmed });
      }
    }
  }
  return results;
}

function normalizeLinkTarget(rawTarget: string): string {
  const trimmed = rawTarget.trim();
  const unwrapped =
    trimmed.startsWith('<') && trimmed.endsWith('>') ? trimmed.slice(1, -1) : trimmed;
  const firstToken = unwrapped.split(/\s+/)[0] ?? '';
  const withoutHash = firstToken.split('#')[0] ?? '';
  const withoutQuery = withoutHash.split('?')[0] ?? '';
  return withoutQuery.trim();
}

function extractPaths(content: string): { line: number; path: string }[] {
  const results: { line: number; path: string }[] = [];
  const seen = new Set<string>();
  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const inlineCodes = lines[i].matchAll(INLINE_CODE_PATTERN);
    for (const match of inlineCodes) {
      const code = match[1];
      const pathMatches = code.matchAll(PATH_PATTERN);
      for (const pm of pathMatches) {
        const candidate = pm[1];
        const key = `${i + 1}:${candidate}`;
        if (!seen.has(key)) {
          seen.add(key);
          results.push({ line: i + 1, path: candidate });
        }
      }
    }

    const markdownLinks = lines[i].matchAll(MARKDOWN_LINK_PATTERN);
    for (const match of markdownLinks) {
      const candidate = normalizeLinkTarget(match[1] ?? '');
      if (!candidate) continue;
      const key = `${i + 1}:${candidate}`;
      if (!seen.has(key)) {
        seen.add(key);
        results.push({ line: i + 1, path: candidate });
      }
    }
  }

  return results;
}

async function pathExistsFromDoc(
  projectRoot: string,
  docFile: string,
  refPath: string,
): Promise<boolean> {
  const normalized = refPath.replace(/^"|"$/g, '').trim();
  const candidates = new Set<string>();
  const docDir = path.dirname(docFile);

  if (normalized.startsWith('/')) {
    candidates.add(path.join(projectRoot, normalized.slice(1)));
  }

  candidates.add(path.resolve(docDir, normalized));
  candidates.add(path.resolve(projectRoot, normalized));

  for (const candidate of candidates) {
    if (await fileExists(candidate)) {
      return true;
    }
  }

  return false;
}

function isLikelyApiEndpointPath(refPath: string): boolean {
  if (!refPath.startsWith('/')) return false;
  if (refPath === '/') return false;

  if (ABSOLUTE_FILESYSTEM_PREFIXES.some((prefix) => refPath.startsWith(prefix))) {
    return false;
  }

  const normalized = refPath.replace(/\/+$/, '');
  const baseName = path.posix.basename(normalized);
  const hasExtension = /\.[A-Za-z0-9]+$/.test(baseName);
  if (hasExtension) {
    return false;
  }

  return true;
}

function normalizeDocReferencePath(refPath: string): string {
  return refPath
    .trim()
    .replace(/^['"`]|['"`]$/g, '')
    .replace(/^\.\//, '');
}

function isCursorCanonicalSharedDocReference(filePath: string, refPath: string): boolean {
  const normalizedFile = filePath.replace(/\\/g, '/');
  if (!normalizedFile.includes('/.cursor/rules/')) {
    return false;
  }
  const normalizedRef = normalizeDocReferencePath(refPath);
  return /^\.claude\/docs\/[a-z0-9._/-]+\.md$/i.test(normalizedRef);
}

const sharedDocsPresenceCache = new Map<string, boolean>();

async function hasAnySharedCanonicalDocs(projectRoot: string): Promise<boolean> {
  const cacheKey = path.resolve(projectRoot);
  const cached = sharedDocsPresenceCache.get(cacheKey);
  if (cached !== undefined) {
    return cached;
  }

  for (const rootDoc of SHARED_ROOT_DOCS) {
    if (await fileExists(path.join(projectRoot, rootDoc))) {
      sharedDocsPresenceCache.set(cacheKey, true);
      return true;
    }
  }

  for (const filename of GENERATED_CLAUDE_DOCS) {
    if (await fileExists(path.join(projectRoot, '.claude', 'docs', filename))) {
      sharedDocsPresenceCache.set(cacheKey, true);
      return true;
    }
  }

  sharedDocsPresenceCache.set(cacheKey, false);
  return false;
}

export async function validateFile(
  filePath: string,
  projectRoot: string,
  scripts: Record<string, string>,
): Promise<ValidationIssue[]> {
  const content = await readFileSafe(filePath);
  if (!content) return [];

  const issues: ValidationIssue[] = [
    ...validateCursorFrontmatter(filePath, content),
    ...validateCursorRuleAdapterQuality(filePath, content),
  ];
  const commands = extractCommands(content);
  const paths = extractPaths(content);

  for (const { line, command } of commands) {
    const parts = command.split(/\s+/);
    const runner = parts[0];
    const scriptName = parts[1] === 'run' ? parts[2] : parts[1];

    if (runner && ['npm', 'yarn', 'pnpm', 'bun'].includes(runner) && scriptName) {
      if (
        parts[1] === 'run' ||
        !['install', 'init', 'create', 'exec', 'dlx', 'i'].includes(parts[1])
      ) {
        if (!scripts[scriptName]) {
          issues.push({
            file: filePath,
            line,
            type: 'missing-command',
            message: `Script "${scriptName}" not found in package.json`,
            reference: command,
          });
        }
      }
    }
  }

  for (const { line, path: refPath } of paths) {
    if (
      refPath.startsWith('http') ||
      refPath.startsWith('#') ||
      refPath.startsWith('mailto:') ||
      isLikelyApiEndpointPath(refPath)
    ) {
      continue;
    }

    if (!(await pathExistsFromDoc(projectRoot, filePath, refPath))) {
      if (
        isCursorCanonicalSharedDocReference(filePath, refPath) &&
        !(await hasAnySharedCanonicalDocs(projectRoot))
      ) {
        continue;
      }
      issues.push({
        file: filePath,
        line,
        type: 'missing-path',
        message: `Path "${refPath}" does not exist`,
        reference: refPath,
      });
    }
  }

  return issues;
}

export async function validateProject(
  projectRoot: string,
  scripts: Record<string, string>,
): Promise<ValidationResult> {
  const docPaths = ['CLAUDE.md', 'AGENTS.md', '.cursor/rules', '.claude/docs'];

  const allIssues: ValidationIssue[] = [];

  for (const docPath of docPaths) {
    const full = path.join(projectRoot, docPath);
    try {
      const stat = await fs.stat(full);
      if (stat.isDirectory()) {
        const entries = await fs.readdir(full);
        for (const entry of entries) {
          if (docPath === '.claude/docs' && !GENERATED_CLAUDE_DOCS.has(entry)) {
            continue;
          }
          if (entry.endsWith('.md') || entry.endsWith('.mdc')) {
            const entryPath = path.join(full, entry);
            allIssues.push(...(await validateFile(entryPath, projectRoot, scripts)));
            if (entry === 'project.mdc') {
              allIssues.push(
                ...validateRootStructure(entryPath, (await readFileSafe(entryPath)) ?? ''),
              );
            }
          }
        }
      } else {
        allIssues.push(...(await validateFile(full, projectRoot, scripts)));
        allIssues.push(...validateRootStructure(full, (await readFileSafe(full)) ?? ''));
      }
    } catch {
      // File/dir doesn't exist, skip
    }
  }

  allIssues.push(...(await validateRootDocsConsistency(projectRoot)));
  allIssues.push(...(await validateQualityGateConsistency(projectRoot)));
  allIssues.push(...(await validateCrossTargetCommandParity(projectRoot, scripts)));
  allIssues.push(...(await validateClaudeCodexRootParity(projectRoot)));
  allIssues.push(...(await validateDocsAgainstProjectFacts(projectRoot)));
  allIssues.push(...(await validateCrossTargetFactConsistency(projectRoot, scripts)));
  allIssues.push(...(await validateCursorCanonicalOverlap(projectRoot)));
  allIssues.push(...(await validateStaleManagedFiles(projectRoot)));

  const errors = allIssues.filter(
    (i) => i.type === 'missing-command' || i.type === 'invalid-root-structure',
  );
  const warnings = allIssues.filter(
    (i) => i.type !== 'missing-command' && i.type !== 'invalid-root-structure',
  );
  const rootDocs = await readRootDocs(projectRoot);
  const score = buildValidationScoreReport(allIssues, {
    hasRootDocs: rootDocs.size > 0,
    hasMultipleRoots: rootDocs.size > 1,
    hasCursorRules: await fileExists(path.join(projectRoot, '.cursor/rules/project.mdc')),
  });

  return {
    valid: errors.length === 0,
    errors,
    warnings,
    score,
  };
}
